// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package pbf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PTGraph struct {
	Map                  *Graph       `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Stop                 []*Stop      `protobuf:"bytes,2,rep,name=stop,proto3" json:"stop,omitempty"`
	SamePlaces           []*SamePlace `protobuf:"bytes,3,rep,name=SamePlaces,proto3" json:"SamePlaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PTGraph) Reset()         { *m = PTGraph{} }
func (m *PTGraph) String() string { return proto.CompactTextString(m) }
func (*PTGraph) ProtoMessage()    {}
func (*PTGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *PTGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTGraph.Unmarshal(m, b)
}
func (m *PTGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTGraph.Marshal(b, m, deterministic)
}
func (m *PTGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTGraph.Merge(m, src)
}
func (m *PTGraph) XXX_Size() int {
	return xxx_messageInfo_PTGraph.Size(m)
}
func (m *PTGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_PTGraph.DiscardUnknown(m)
}

var xxx_messageInfo_PTGraph proto.InternalMessageInfo

func (m *PTGraph) GetMap() *Graph {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *PTGraph) GetStop() []*Stop {
	if m != nil {
		return m.Stop
	}
	return nil
}

func (m *PTGraph) GetSamePlaces() []*SamePlace {
	if m != nil {
		return m.SamePlaces
	}
	return nil
}

type SamePlace struct {
	Place                int64         `protobuf:"varint,1,opt,name=place,proto3" json:"place,omitempty"`
	SamePlaces           []*MultiPlace `protobuf:"bytes,2,rep,name=SamePlaces,proto3" json:"SamePlaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SamePlace) Reset()         { *m = SamePlace{} }
func (m *SamePlace) String() string { return proto.CompactTextString(m) }
func (*SamePlace) ProtoMessage()    {}
func (*SamePlace) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *SamePlace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SamePlace.Unmarshal(m, b)
}
func (m *SamePlace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SamePlace.Marshal(b, m, deterministic)
}
func (m *SamePlace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SamePlace.Merge(m, src)
}
func (m *SamePlace) XXX_Size() int {
	return xxx_messageInfo_SamePlace.Size(m)
}
func (m *SamePlace) XXX_DiscardUnknown() {
	xxx_messageInfo_SamePlace.DiscardUnknown(m)
}

var xxx_messageInfo_SamePlace proto.InternalMessageInfo

func (m *SamePlace) GetPlace() int64 {
	if m != nil {
		return m.Place
	}
	return 0
}

func (m *SamePlace) GetSamePlaces() []*MultiPlace {
	if m != nil {
		return m.SamePlaces
	}
	return nil
}

type MultiPlace struct {
	Graphid              int32    `protobuf:"varint,1,opt,name=graphid,proto3" json:"graphid,omitempty"`
	Place                int64    `protobuf:"varint,2,opt,name=place,proto3" json:"place,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiPlace) Reset()         { *m = MultiPlace{} }
func (m *MultiPlace) String() string { return proto.CompactTextString(m) }
func (*MultiPlace) ProtoMessage()    {}
func (*MultiPlace) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *MultiPlace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiPlace.Unmarshal(m, b)
}
func (m *MultiPlace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiPlace.Marshal(b, m, deterministic)
}
func (m *MultiPlace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiPlace.Merge(m, src)
}
func (m *MultiPlace) XXX_Size() int {
	return xxx_messageInfo_MultiPlace.Size(m)
}
func (m *MultiPlace) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiPlace.DiscardUnknown(m)
}

var xxx_messageInfo_MultiPlace proto.InternalMessageInfo

func (m *MultiPlace) GetGraphid() int32 {
	if m != nil {
		return m.Graphid
	}
	return 0
}

func (m *MultiPlace) GetPlace() int64 {
	if m != nil {
		return m.Place
	}
	return 0
}

type Stop struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StopId               string   `protobuf:"bytes,3,opt,name=StopId,proto3" json:"StopId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop) Reset()         { *m = Stop{} }
func (m *Stop) String() string { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()    {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *Stop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop.Unmarshal(m, b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return xxx_messageInfo_Stop.Size(m)
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

func (m *Stop) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Stop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stop) GetStopId() string {
	if m != nil {
		return m.StopId
	}
	return ""
}

type Graph struct {
	Edge                 []*Edge   `protobuf:"bytes,1,rep,name=edge,proto3" json:"edge,omitempty"`
	Latlon               []*LatLon `protobuf:"bytes,2,rep,name=latlon,proto3" json:"latlon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetEdge() []*Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

func (m *Graph) GetLatlon() []*LatLon {
	if m != nil {
		return m.Latlon
	}
	return nil
}

type Edge struct {
	EdgeId               int64    `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	From                 int64    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Cost                 float64  `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	PointId              []int64  `protobuf:"varint,5,rep,packed,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetEdgeId() int64 {
	if m != nil {
		return m.EdgeId
	}
	return 0
}

func (m *Edge) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Edge) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Edge) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Edge) GetPointId() []int64 {
	if m != nil {
		return m.PointId
	}
	return nil
}

type LatLon struct {
	LatlonId             int64    `protobuf:"varint,1,opt,name=latlon_id,json=latlonId,proto3" json:"latlon_id,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLon) Reset()         { *m = LatLon{} }
func (m *LatLon) String() string { return proto.CompactTextString(m) }
func (*LatLon) ProtoMessage()    {}
func (*LatLon) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *LatLon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLon.Unmarshal(m, b)
}
func (m *LatLon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLon.Marshal(b, m, deterministic)
}
func (m *LatLon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLon.Merge(m, src)
}
func (m *LatLon) XXX_Size() int {
	return xxx_messageInfo_LatLon.Size(m)
}
func (m *LatLon) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLon.DiscardUnknown(m)
}

var xxx_messageInfo_LatLon proto.InternalMessageInfo

func (m *LatLon) GetLatlonId() int64 {
	if m != nil {
		return m.LatlonId
	}
	return 0
}

func (m *LatLon) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLon) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*PTGraph)(nil), "pbf.PTGraph")
	proto.RegisterType((*SamePlace)(nil), "pbf.SamePlace")
	proto.RegisterType((*MultiPlace)(nil), "pbf.MultiPlace")
	proto.RegisterType((*Stop)(nil), "pbf.Stop")
	proto.RegisterType((*Graph)(nil), "pbf.Graph")
	proto.RegisterType((*Edge)(nil), "pbf.Edge")
	proto.RegisterType((*LatLon)(nil), "pbf.LatLon")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xdf, 0x6b, 0xa3, 0x40,
	0x10, 0x46, 0xd7, 0x1f, 0x71, 0x84, 0xdc, 0x31, 0x1c, 0x77, 0x1e, 0x77, 0x01, 0xb1, 0x2f, 0x3e,
	0x59, 0x48, 0x5f, 0xfb, 0x54, 0x28, 0x45, 0x9a, 0x96, 0xb0, 0xe9, 0x7b, 0xd9, 0x44, 0x93, 0x0a,
	0xea, 0x2e, 0x66, 0xdb, 0xbf, 0xbf, 0xec, 0xac, 0x89, 0x29, 0x7d, 0x91, 0xf9, 0xbe, 0xf9, 0x66,
	0xbe, 0x6f, 0x16, 0x21, 0x56, 0x83, 0xd4, 0xb2, 0xa0, 0x2f, 0x32, 0xb5, 0xdd, 0x67, 0x1f, 0x10,
	0xae, 0x5f, 0x1e, 0x06, 0xa1, 0xde, 0xf0, 0x3f, 0xb0, 0x4e, 0xa8, 0xc4, 0x49, 0x9d, 0x3c, 0x5e,
	0x42, 0xa1, 0xb6, 0xfb, 0x82, 0x1a, 0xdc, 0xd0, 0xb8, 0x00, 0xef, 0xa8, 0xa5, 0x4a, 0xdc, 0x94,
	0xe5, 0xf1, 0x32, 0xa2, 0xf6, 0x46, 0x4b, 0xc5, 0x89, 0xc6, 0x02, 0x60, 0x23, 0xba, 0x7a, 0xdd,
	0x8a, 0x5d, 0x7d, 0x4c, 0x18, 0x89, 0xe6, 0x56, 0x74, 0xa2, 0xf9, 0x85, 0x22, 0xe3, 0x10, 0x9d,
	0x11, 0xfe, 0x02, 0x5f, 0x99, 0x82, 0xbc, 0x19, 0xb7, 0x00, 0xaf, 0xbf, 0xac, 0xb4, 0xbe, 0x3f,
	0x68, 0xe5, 0xd3, 0x7b, 0xab, 0x9b, 0xef, 0x3b, 0x6f, 0x01, 0xa6, 0x0e, 0x26, 0x10, 0x1e, 0x4c,
	0xfc, 0xa6, 0xa2, 0xb5, 0x3e, 0x3f, 0xc1, 0xc9, 0xce, 0xbd, 0xb0, 0xcb, 0xee, 0xc0, 0x33, 0xf7,
	0xe0, 0x1c, 0xdc, 0x71, 0x84, 0x71, 0xb7, 0xa9, 0x10, 0xc1, 0x7b, 0x16, 0x9d, 0x15, 0x47, 0x9c,
	0x6a, 0xfc, 0x0d, 0x81, 0xd1, 0x96, 0x55, 0xc2, 0x88, 0x1d, 0x51, 0xf6, 0x08, 0xbe, 0x7d, 0xcb,
	0x05, 0x78, 0x75, 0x75, 0x30, 0x07, 0x4d, 0xaf, 0x75, 0x5f, 0x1d, 0x6a, 0x4e, 0x34, 0x5e, 0x41,
	0xd0, 0x0a, 0xdd, 0xca, 0x7e, 0x3c, 0x2b, 0x26, 0xc1, 0x4a, 0xe8, 0x95, 0xec, 0xf9, 0xd8, 0xca,
	0x06, 0xf0, 0xcc, 0x08, 0xfe, 0x81, 0xd0, 0x0c, 0xbd, 0x9e, 0x53, 0x05, 0x06, 0x96, 0x94, 0x6c,
	0x3f, 0xc8, 0x6e, 0x3c, 0x83, 0x6a, 0x93, 0x5e, 0x4b, 0x4a, 0xc5, 0xb8, 0xab, 0xa5, 0xd1, 0xec,
	0xe4, 0x51, 0x27, 0x5e, 0xea, 0xe4, 0x0e, 0xa7, 0x1a, 0xff, 0xc2, 0x4c, 0xc9, 0xa6, 0xd7, 0x66,
	0xa3, 0x9f, 0xb2, 0x9c, 0xf1, 0x90, 0x70, 0x59, 0x65, 0x25, 0x04, 0x36, 0x05, 0xfe, 0x83, 0xc8,
	0xe6, 0x98, 0x7c, 0x67, 0x96, 0x28, 0x2b, 0xfc, 0x09, 0xac, 0x15, 0x9a, 0x8c, 0x1d, 0x6e, 0x4a,
	0x62, 0x64, 0x4f, 0xc6, 0x86, 0x91, 0xfd, 0x36, 0xa0, 0xbf, 0xec, 0xe6, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x05, 0xe6, 0x0c, 0x08, 0x74, 0x02, 0x00, 0x00,
}
